# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

defaults:
  - database: default
  - entities: default
  - masking: default

out: "/glusterfs/dfs-gfs-dist/barthfab/pedl/pedl/PEDL_predictions/out"
out_blinded: "/glusterfs/dfs-gfs-dist/barthfab/pedl/pedl/PEDL_predictions/out_blinded"
expand_species: null
triples: ???
pubtator: localhost:4243
chemprot: true

n_worker: 1
worker_id: 0
