# path to original working directory
# hydra hijacks working directory by changing it to the current log directory,
# so it's useful to have this path as a special variable
# learn more here: https://hydra.cc/docs/next/tutorials/basic/running_your_app/working_directory
work_dir: ${hydra:runtime.cwd}

defaults:
  - _self_
  - database: default
  - entities: default
  - masking: default

e1: ???
e2: ???
type1: ???
type2: ???

out: "PEDL_predictions"
model: "barthfab/drugprot"
batch_size: 1
pubtator: #localhost:9200
#localhost:4243
device: cpu
topk: False
cutoff: 0.01
max_bag_size: 1000
api_fallback: False
skip_reverse: False
skip_invalid: False
verbose: False
expand_species:
multi_sentence: False
num_workers: 1
worker_id: 0
local_model: False
max_sequence_length: 512
use_cls: False
use_starts: False
use_ends: False
entity_embeddings: True